### ISSUE TITLE
There's no constant named error and pub get error

### ISSUE THREAD

**Issue by Karwann** [woosignal/flutter-woocommerce-app#11]
i have 5 error in dart analysis 
`error: There's no constant named 'downToUp' in 'PageTransitionType'. (undefined_enum_constant at [label_storemax] lib\main.dart:87)
`
and when i run pub get i get this error 
```
Warning: You are using these overridden dependencies:
! intl 0.16.1
```

**Comment by agordn52** [comment]
Looks like you ran `flutter pub upgrade` instead of `flutter pub get`.
Clean your project with `flutter clean` and then run `flutter pub get`.

We released v2.2.0 today which includes dependency updates so you can use that version.
The warning you see in the console re. intl you can ignore.

Closing #11
